name: Android CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        jdk-version: ["11"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment v${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing node dependencies
        run: npm install
      - name: Ionic build
        run: npm run ionBuild
      - name: Ionic add android
        run: npm run ionAdd:android
      - name: set up JDK ${{ matrix.jdk-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk-version }}
          distribution: "temurin"
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: android
